-- AlterTable
ALTER TABLE "public"."Property" ADD COLUMN     "guests" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "rooms" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "size" DOUBLE PRECISION NOT NULL DEFAULT 0;
